defmodule MigrationSeeds do
  alias PokerEx.PrivateRoom
  import PokerEx.TestHelpers

  def seed do
    player = insert_user()

    for room_data <- old_room_data() do
      PrivateRoom.create(room_data.room_id, player, [])
      PrivateRoom.get_room_and_store_state(room_data.room_id, room_data.phase, room_data)
    end
  end

  def old_room_data do
    [
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :clubs},
            %PokerEx.Card{rank: :seven, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :diamonds},
            %PokerEx.Card{rank: :five, suit: :clubs}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "mygame",
        round: %{},
        seating: [],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [{"Zack", 1}, {"Zack Kayser", 0}],
        all_in: [],
        called: ["Zack Kayser"],
        chip_roll: %{"Zack" => 170, "Zack Kayser" => 205},
        current_big_blind: 1,
        current_small_blind: 0,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :seven, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :clubs},
            %PokerEx.Card{rank: :five, suit: :clubs},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :spades},
            %PokerEx.Card{rank: :queen, suit: :hearts},
            %PokerEx.Card{rank: :king, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :ten, suit: :spades},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :four, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :diamonds},
            %PokerEx.Card{rank: :ten, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :six, suit: :clubs}
          ],
          dealt: [
            [
              %PokerEx.Card{rank: :six, suit: :hearts},
              %PokerEx.Card{rank: :five, suit: :diamonds}
            ],
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :hearts}
          ]
        },
        folded: [],
        paid: %{"Zack" => 10, "Zack Kayser" => 15},
        parent: nil,
        phase: :pre_flop,
        player_hands: [
          {"Zack Kayser",
           [
             %PokerEx.Card{rank: :four, suit: :diamonds},
             %PokerEx.Card{rank: :four, suit: :hearts}
           ]},
          {"Zack",
           [
             %PokerEx.Card{rank: :six, suit: :hearts},
             %PokerEx.Card{rank: :five, suit: :diamonds}
           ]}
        ],
        pot: 25,
        rewards: [],
        room_id: "First_ever_poker-ex_prod_game",
        round: %{"Zack" => 10, "Zack Kayser" => 15},
        seating: [{"Zack Kayser", 0}, {"Zack", 1}],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 10,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [{"Norris", 1}, {"Zack", 0}],
        all_in: [],
        called: ["Zack"],
        chip_roll: %{"Norris" => 1_000_001_010, "Zack" => 400_165},
        current_big_blind: 1,
        current_small_blind: 0,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :six, suit: :clubs},
            %PokerEx.Card{rank: :ten, suit: :spades},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :three, suit: :clubs},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :hearts},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :hearts},
            %PokerEx.Card{rank: :jack, suit: :hearts},
            %PokerEx.Card{rank: :seven, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :clubs},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :clubs},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :five, suit: :spades}
          ],
          dealt: [
            [
              %PokerEx.Card{rank: :nine, suit: :spades},
              %PokerEx.Card{rank: :eight, suit: :spades}
            ],
            %PokerEx.Card{rank: :king, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :hearts}
          ]
        },
        folded: [],
        paid: %{"Norris" => 10, "Zack" => 15},
        parent: nil,
        phase: :pre_flop,
        player_hands: [
          {"Zack",
           [
             %PokerEx.Card{rank: :king, suit: :diamonds},
             %PokerEx.Card{rank: :eight, suit: :hearts}
           ]},
          {"Norris",
           [
             %PokerEx.Card{rank: :nine, suit: :spades},
             %PokerEx.Card{rank: :eight, suit: :spades}
           ]}
        ],
        pot: 25,
        rewards: [],
        room_id: "Player_Haters_Ball",
        round: %{"Norris" => 10, "Zack" => 15},
        seating: [{"Zack", 0}, {"Norris", 1}],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 10,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :clubs},
            %PokerEx.Card{rank: :seven, suit: :spades}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "Tralala",
        round: %{},
        seating: [],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{"killermike" => 201},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :clubs}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "dope",
        round: %{},
        seating: [{"killermike", 0}],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :diamonds}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "testing_out",
        round: %{},
        seating: [],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{"okedeh" => 465},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :clubs}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "asdaf",
        round: %{},
        seating: [{"okedeh", 0}],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{"Zack" => 3200},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :three, suit: :hearts}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "Zzz",
        round: %{},
        seating: [{"Zack", 0}],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "Room_1",
        round: %{},
        seating: [],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [],
        all_in: [],
        called: [],
        chip_roll: %{},
        current_big_blind: nil,
        current_small_blind: nil,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :three, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :diamonds}
          ],
          dealt: nil
        },
        folded: [],
        paid: %{},
        parent: nil,
        phase: :idle,
        player_hands: [],
        pot: 0,
        rewards: [],
        room_id: "fdfa,sdmfasdf",
        round: %{},
        seating: [],
        skip_advance?: false,
        stats: [],
        table: [],
        timeout: :infinity,
        timer: nil,
        to_call: 0,
        type: :private,
        winner: nil,
        winning_hand: nil
      },
      %{
        active: [{"YourMom", 0}, {"cubsker", 1}],
        all_in: [],
        called: ["cubsker"],
        chip_roll: %{"YourMom" => 87, "cubsker" => 53},
        current_big_blind: 0,
        current_small_blind: 1,
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :ace, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :spades},
            %PokerEx.Card{rank: :four, suit: :hearts},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :five, suit: :spades},
            %PokerEx.Card{rank: :six, suit: :clubs},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :eight, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :clubs},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :diamonds}
          ],
          dealt: [
            [%PokerEx.Card{rank: :ace, suit: :spades}],
            [%PokerEx.Card{rank: :two, suit: :clubs}],
            [%PokerEx.Card{rank: :seven, suit: :diamonds}],
            [%PokerEx.Card{rank: :six, suit: :spades}],
            [%PokerEx.Card{rank: :three, suit: :hearts}],
            [
              %PokerEx.Card{rank: :four, suit: :spades},
              %PokerEx.Card{rank: :queen, suit: :spades}
            ],
            %PokerEx.Card{rank: :ten, suit: :spades},
            %PokerEx.Card{rank: :three, suit: :clubs}
          ]
        },
        folded: [],
        paid: %{"YourMom" => 370, "cubsker" => 490},
        parent: nil,
        phase: :river,
        player_hands: [
          {"cubsker",
           [
             %PokerEx.Card{rank: :ten, suit: :spades},
             %PokerEx.Card{rank: :three, suit: :clubs}
           ]},
          {"YourMom",
           [
             %PokerEx.Card{rank: :four, suit: :spades},
             %PokerEx.Card{rank: :queen, suit: :spades}
           ]}
        ],
        pot: 860,
        rewards: [],
        room_id: "???",
        round: %{"YourMom" => 333, "cubsker" => 448},
        seating: [{"YourMom", 0}, {"cubsker", 1}],
        skip_advance?: false,
        stats: [],
        table: [
          %PokerEx.Card{rank: :three, suit: :hearts},
          %PokerEx.Card{rank: :six, suit: :spades},
          %PokerEx.Card{rank: :seven, suit: :diamonds},
          %PokerEx.Card{rank: :two, suit: :clubs},
          %PokerEx.Card{rank: :ace, suit: :spades}
        ],
        timeout: :infinity,
        timer: nil,
        to_call: 338,
        type: :private,
        winner: nil,
        winning_hand: nil
      }
    ]
  end

  def expected_game do
    %PokerEx.GameEngine.Impl{
      async_manager: %PokerEx.GameEngine.AsyncManager{},
      chips: %PokerEx.GameEngine.ChipManager{
        chip_roll: %{"Norris" => 1_000_001_010, "Zack" => 400_165},
        round: %{"Norris" => 10, "Zack" => 15},
        paid: %{"Norris" => 10, "Zack" => 15},
        to_call: 10,
        pot: 25
      },
      seating: %PokerEx.GameEngine.Seating{arrangement: [{"Zack", 0}, {"Norris", 1}]},
      player_tracker: %PokerEx.GameEngine.PlayerTracker{
        active: ["Norris", "Zack"],
        all_in: [],
        called: ["Zack"],
        folded: []
      },
      cards: %PokerEx.GameEngine.CardManager{
        table: [],
        deck: %PokerEx.Deck{
          cards: [
            %PokerEx.Card{rank: :two, suit: :spades},
            %PokerEx.Card{rank: :six, suit: :clubs},
            %PokerEx.Card{rank: :ten, suit: :spades},
            %PokerEx.Card{rank: :seven, suit: :clubs},
            %PokerEx.Card{rank: :five, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :spades},
            %PokerEx.Card{rank: :three, suit: :clubs},
            %PokerEx.Card{rank: :four, suit: :clubs},
            %PokerEx.Card{rank: :jack, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :clubs},
            %PokerEx.Card{rank: :king, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :diamonds},
            %PokerEx.Card{rank: :seven, suit: :spades},
            %PokerEx.Card{rank: :two, suit: :hearts},
            %PokerEx.Card{rank: :four, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :clubs},
            %PokerEx.Card{rank: :queen, suit: :diamonds},
            %PokerEx.Card{rank: :five, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :diamonds},
            %PokerEx.Card{rank: :king, suit: :hearts},
            %PokerEx.Card{rank: :six, suit: :hearts},
            %PokerEx.Card{rank: :three, suit: :hearts},
            %PokerEx.Card{rank: :three, suit: :diamonds},
            %PokerEx.Card{rank: :queen, suit: :spades},
            %PokerEx.Card{rank: :ace, suit: :hearts},
            %PokerEx.Card{rank: :nine, suit: :hearts},
            %PokerEx.Card{rank: :ten, suit: :hearts},
            %PokerEx.Card{rank: :jack, suit: :hearts},
            %PokerEx.Card{rank: :seven, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :clubs},
            %PokerEx.Card{rank: :ace, suit: :spades},
            %PokerEx.Card{rank: :jack, suit: :clubs},
            %PokerEx.Card{rank: :ten, suit: :clubs},
            %PokerEx.Card{rank: :eight, suit: :diamonds},
            %PokerEx.Card{rank: :two, suit: :diamonds},
            %PokerEx.Card{rank: :five, suit: :spades}
          ],
          dealt: [
            %PokerEx.Card{rank: :nine, suit: :spades},
            %PokerEx.Card{rank: :eight, suit: :spades},
            %PokerEx.Card{rank: :king, suit: :diamonds},
            %PokerEx.Card{rank: :eight, suit: :hearts}
          ]
        },
        player_hands: [
          %{
            player: "Zack",
            hand: [
              %PokerEx.Card{rank: :king, suit: :diamonds},
              %PokerEx.Card{rank: :eight, suit: :hearts}
            ]
          },
          %{
            player: "Norris",
            hand: [
              %PokerEx.Card{rank: :nine, suit: :spades},
              %PokerEx.Card{rank: :eight, suit: :spades}
            ]
          }
        ]
      },
      scoring: %PokerEx.GameEngine.ScoreManager{},
      roles: %PokerEx.GameEngine.RoleManager{
        dealer: 1,
        big_blind: 1,
        small_blind: 0
      },
      type: :private,
      game_id: "Player_Haters_Ball",
      phase: :pre_flop,
      timeout: 30_000
    }
  end
end
